 version: '3.7'
 services:
  
   dashboard:
     build: 
       context: ./
     container_name: pygrokdebugger      
     hostname: "PyGrokDash"
     restart: always
     ports:
       - 8060:80
     networks:
       - network
     command: gunicorn --worker-tmp-dir /dev/shm --workers=4 --threads=4 --worker-class=gthread  -b :80 app:server
    
 networks:
   network:
     driver: bridge
